### ISSUE TITLE
Allow to disable URL Preview

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#293]
Hi there,

when working with via wire, it tends to be quite annoying when all urls are previewed  instantly. This makes the chat very verbose and allows to display very little chat history.

Thus this proposal to allow disabling this preview, which I envision to accomplish some things:
* More compact history so easier to work with

(less important, but hey)
* Less battery usage

**Comment by herrmannplatz** [comment]
We are experimenting with a smaller layout for link previews in general. 

But i will also vote for an option to disable sending of link previews, since there are a lot of links that doesnt benefit from having a preview.

**Comment by lipis** [comment]
I think deleting it afterwards (like in Slack) would be the best option..

**Comment by gregor** [comment]
I like the approach clients from other messengers that that they show you the preview before sending and enable the user to remove them from the message. Disabling the alltogether from the preferences is a nice to have then.

**Comment by dwt** [comment]
> I like the approach clients from other messengers that that they show you the preview before sending and enable the user to remove them from the message. Disabling the alltogether from the preferences is a nice to have then.
> 
While this sounds nice, I’d like to add that this is not working for our use case. We talk about stuff that is named like urls quite a bit, having to manually remove the preview every time will just not cut it (i.e. be just as annoying as having the client insert them into the conversation all the time).

**Comment by herrmannplatz** [comment]
Still prefer the global switch in the settings.

**Comment by manasb** [comment]
I'd like the optoin to disable these, I'm not sure what happens when something like a `*.onion` URL is shared but if Wire tries to do a DNS query then that may leak the URL?

**Comment by bill-mcgonigle** [comment]
TFW you do a carefully-guarded Tor search to find a link and then send it to your friend over Wire to keep it encrypted, and Wire turns around and sends the URL out cleartext from your device.  Oh, dear - that could cause some very, very real problems.  Data leaking should *not* be the default.

**Comment by manasb** [comment]
@bill-mcgonigle Yeah, a rather silly oversight, in my opinion for a piece of software that touts itself to be "privacy respecting".

**Comment by dwt** [comment]
I'd like to add that the link preview is also way too aggressive. for example, when I posted this (which is highlighted correctly in wire 👍)

    ```python
    def is_ending(self):
            return self.is_next_all_player_step('EndRun')
        
        def has_ended(self):
            return self._already_called.get('destroy', False)
    ```

wire thinks it has found a link to 'self' in there. Ok, that's probably also it's own bug, but just being able to disable link previews would also solve this.

**Comment by gregor** [comment]
We have added a preference to disable link preview generation on the sender side. We are still experimenting internally with the rich content display on the receiver side but the issue of possibly leaking the IP due with this feature has been addressed and I am thereby closing this issue.

**Comment by hylkevds** [comment]
The previewer still shows youtube videos in-line, even with link preview generation disabled.

**Comment by njbart** [comment]
It seems that when generating previews, wire is still leaking youtube and possibly other links on both the sender and receiver side. (This is on macOS, wire "Version 3.3.2862 / Wire for Web Version 2018.10.02.0803".) As @bill-mcgonigle pointed out before, this might result in a highly problematic breach of privacy. For a "privacy respecting" app, this is indeed inacceptable. 

An option to turn off this behaviour *reliably* would indeed be very high on my wishlist. Another way of dealing with this issue might be to route such requests via tor – have you considered this?

**Comment by Transisto** [comment]
I think URLs in `code` should not generate previews.
